{"uuid":"c945aad2-dd21-4892-92dc-831b3e578f87","historyId":"c59643030e1e776644fd5d1d6aa79cfc","status":"failed","statusDetails":{"message":"The following error originated from your test code, not from Cypress.\n\n  > undefined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","trace":"Error: The following error originated from your test code, not from Cypress.\n\n  > undefined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure."},"stage":"finished","steps":[],"attachments":[],"parameters":[],"labels":[{"name":"package","value":"cypress\\e2e\\gigmLogin.cy.js"}],"links":[],"start":1681281201971,"name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","stop":1681281202763}